adminDomainName: http://127.0.0.1:8080/
server:
  port: 8080
  jwtKey : qcxx-admin
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: qcxx
  username: root
  password: root
  charset: utf8mb4
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 1
